language: node_js
before_script:
- npm install -g bower
- bower install
- "./prebuild.sh"
script:
- docpad deploy-ghpages --env static
env:
  global:
    secure: O9A3iacbbu5EaN92ikPZJRLFPG0sfRuDTtuj5A9mXXMxBZbKCSWYnvXfwcH1mzag0BlRCu7zN6ce1WV/Zg4Uqd8WpoPEPCHtxts8I2cJA5OEHNaZn5wRYPVURucgPJT65d3GIiAomaNJRX7uT5Yf0aIvE7jr/i1PAuOh9ZbAySsfdKq3lUTIWc2NEH7Sui5u0f1mKEiDbpRGGRRwepvd1P29DQWYS17vo6y2TOcBo1oShlYjr0h7wPaohEtImifu4WI1pukMQfKp70PoGkvfndMJXdi8Zfj2cd1yI1yg6GK+a3GD+5T0pwy8X1tUbfLH9LZfifn1FRMJwjkU5GvyO6IV74AzEVcbpqxB6CCeg0ojB5rlO0QhyAwo2RHYxxWSE72xTUoy2PsiOaiXjbNMNlqTANKFcA9TtBguJI12PnfGrz6cKx3im00TeKaFH73aj0cexvIjj02btD3+MQnZrwggSjkR2Y3OTULEOiXkHz6zV+P8RaotNt5yDrXIxY/8JlUXXVTAA81sLMUFAjiUTkfUmOpazROqt7jl7IPziORaZp0hst1JNqbqiL10zwDlXvor6F1amN1EQJD/TX1GgR7vUW1tB1QzNUs8XvxBwn8GiNNqDTslwk1B74SjZHQ4f53CoepxmKH3h7Nx9z5S9WMaFoP205g98etLWIIhPhQ=
